#!/bin/bash
echo "Teensy Upload Helper"
echo "===================="
echo ""
echo "Option 1: GUI Loader (recommended for first time)"
echo "  Run: ./teensy .pio/build/teensy40/firmware.hex"
echo "  Then press the button on your Teensy"
echo ""
echo "Option 2: Command line upload"
echo "  1. Unplug and replug the Teensy USB cable"
echo "  2. Press the button on the Teensy"
echo "  3. Within 5 seconds run:"
echo "     ~/.local/bin/pio run --target upload"
echo ""
echo "Option 3: Using sudo (if permissions still fail)"
echo "  sudo ~/.local/bin/pio run --target upload"
echo ""
echo "The firmware file is ready at: .pio/build/teensy40/firmware.hex"